{- |
Module      : BNFC.Backend.LeanMenhir
Description : Top-level Lean 4 backend using the verified LeanMenhir LR(1) parser.

Emits a runnable Lean 4 project whose parser is generated by the
verified LeanMenhir LR(1) runtime (a Lean port of @coq-menhirlib@). The
emitted parser carries a per-grammar @native_decide@ certificate that
the SLR(1) tables are sound and complete for the grammar (axiom set:
@{propext, Quot.sound, _native_decide_…}@; the third is the standard
compiled-code-trust axiom).

Most of the emitted files (abstract syntax, lexer, printer, test driver,
runtime token type) are reused unchanged from the plain @--lean@ backend
(see "BNFC.Backend.Lean"). Only the parser module is different: instead
of a hand-rolled recursive-descent / PEG parser, this backend emits a
@Grammar0@ definition, the @build_tables%@ invocation, the typed action
dispatcher (with @LeanMenhir.Gen.elimOutOfRange@ exhaustiveness shim),
and the @parseWith@-based driver.

Scaling: small grammars (calc, stmcalc) elaborate and build in seconds.
L0-sized grammars (256 productions / 480 SLR(1) states) build in roughly
20 minutes end-to-end on a recent laptop — the bulk of that is
@native_decide@ compiling and running the @safe@/@complete@ validators
against the 480-state automaton; the *runtime* parser is O(n) in input
length (~0.24 s on an 84k-token L0 input).  Build cost is a one-time
hit cacheable in @.lake/@.

Dependencies: requires LeanMenhir at @main@ ≥ commit @31bbad44@
(the O(1) token buffer + de-Mathlib-refactor; the jump-tree action-
dispatcher fix from earlier is also included).  The emitted
@lakefile.toml@ @path@-requires LeanMenhir from a fixed local checkout;
switch to a @git@ require for distribution.  Generated projects no
longer depend on Mathlib, so @lake exe cache get@ is no longer needed.
-}

module BNFC.Backend.LeanMenhir ( makeLeanMenhir ) where

import BNFC.Backend.Base
import BNFC.CF
import BNFC.Options ( SharedOptions(..) )

import qualified BNFC.Backend.Common.Makefile as Makefile

-- Reuse the existing Lean abstract-syntax, lexer, printer, test driver
-- and runtime (only the lexer-facing types from the runtime are needed —
-- the parser-monad combinators in the runtime are unused but harmless).
import BNFC.Backend.Lean.CFtoLeanAbs     ( cf2Abstract )
import BNFC.Backend.Lean.CFtoLeanLex     ( cf2Lex )
import BNFC.Backend.Lean.CFtoLeanPrinter ( cf2Printer )
import BNFC.Backend.Lean.CFtoLeanRuntime ( runtimeContent )
import BNFC.Backend.Lean.CFtoLeanTest    ( cf2Test )
import BNFC.Backend.Lean.LeanUtil

import BNFC.Backend.LeanMenhir.CFtoLeanMenhirPar
  ( cf2LeanMenhirParTables
  , cf2LeanMenhirParSafe
  , cf2LeanMenhirParComplete
  , cf2LeanMenhirParUmbrella
  )

import BNFC.PrettyPrint ( vcat, text, Doc )

-- | Top-level entrypoint dispatched from @Main.hs@.
makeLeanMenhir :: SharedOptions -> CF -> Backend
makeLeanMenhir opts cf = do
  let absMod          = absLeanModule          opts
      lexMod          = lexLeanModule          opts
      parMod          = parLeanModule          opts
      parTablesMod    = parTablesLeanModule    opts
      parSafeMod      = parSafeLeanModule      opts
      parCompleteMod  = parCompleteLeanModule  opts
      printMod        = printLeanModule        opts
      testMod         = testLeanModule         opts
      runtimeMod      = runtimeLeanModule      opts

  mkfile (runtimeLeanFile      opts) leanComment $ runtimeContent runtimeMod
  mkfile (absLeanFile          opts) leanComment $ cf2Abstract absMod cf
  mkfile (lexLeanFile          opts) leanComment $ cf2Lex      lexMod   runtimeMod cf

  -- Parser, split across four modules so Lake can parallelise the two
  -- `native_decide` certificates.  All four files share the umbrella
  -- namespace (`parMod`), so `<umbrella>.parseExp` etc. are flat names
  -- from downstream code's point of view.  See the module header of
  -- "BNFC.Backend.LeanMenhir.CFtoLeanMenhirPar" for the build DAG.
  mkfile (parTablesLeanFile    opts) leanComment $
    cf2LeanMenhirParTables parTablesMod parMod absMod runtimeMod cf
  mkfile (parSafeLeanFile      opts) leanComment $
    cf2LeanMenhirParSafe parSafeMod parTablesMod parMod absMod lexMod runtimeMod cf
  mkfile (parCompleteLeanFile  opts) leanComment $
    cf2LeanMenhirParComplete parCompleteMod parTablesMod parMod
  mkfile (parLeanFile          opts) leanComment $
    cf2LeanMenhirParUmbrella parMod parTablesMod parSafeMod parCompleteMod

  mkfile (printLeanFile        opts) leanComment $ cf2Printer  printMod absMod cf
  mkfile (testLeanFile         opts) leanComment $
    cf2Test testMod absMod parMod printMod runtimeMod cf

  mkfile lakeFile      ("# " ++) $ lakefileContent opts
  mkfile leanToolchainFile (const "") leanToolchainContent

  Makefile.mkMakefile (optMake opts) (makefile opts)

----------------------------------------------------------------------------
-- Project files
----------------------------------------------------------------------------

-- | LeanMenhir is pinned to Lean 4.31.0 (Mathlib v4.31.0).  The
--   generated project must use the SAME toolchain (this file is read by
--   elan to pick the compiler).
leanToolchainContent :: String
leanToolchainContent = "leanprover/lean4:v4.31.0\n"

-- | Local checkout of LeanMenhir.  For now we hardcode a developer
--   path; for distribution, replace with a @git@ require pinned to a
--   commit or tag.
leanMenhirLocalPath :: FilePath
leanMenhirLocalPath = "/home/gavinzjw/Menhir/LeanMenhir"

lakefileContent :: SharedOptions -> String
lakefileContent opts = unlines
  [ "name = \"" ++ projectName ++ "\""
  , "defaultTargets = [\"" ++ exeName ++ "\"]"
  , ""
  , "# LeanMenhir provides the verified LR(1) parser interpreter + SLR(1)"
  , "# table generator.  As of the de-Mathlib refactor it has NO Mathlib"
  , "# dependency, so no `lake exe cache get` is needed; `lake build` alone"
  , "# is enough.  (`lake update` is needed once to fetch LeanMenhir's only"
  , "# remaining transitive dep, `repl`, which it keeps for LSP tooling.)"
  , "[[require]]"
  , "name = \"LeanMenhir\""
  , "path = \"" ++ leanMenhirLocalPath ++ "\""
  , "# Or, for distribution, replace with a git require pinned to a known-good"
  , "# commit.  The BNFC emitter currently expects the API surface as of"
  , "# leanmenhir-commit 31bbad4411855c0ac1a2211c207b4bb69e5ebe3e or newer:"
  , "# git  = \"https://github.com/GZGavinZhao/LeanMenhir.git\""
  , "# rev  = \"31bbad4411855c0ac1a2211c207b4bb69e5ebe3e\""
  , ""
  , "[[lean_lib]]"
  , "name = \"" ++ projectName ++ "\""
  , "# All four parser modules are listed as roots so `lake build :" ++ projectName ++ "`"
  , "# builds them as a DAG: Tables → (Safe ‖ Complete) → umbrella.  Lake"
  , "# runs the two `native_decide` jobs (Safe and Complete) in parallel."
  , "roots = [\"" ++ runtimeLeanModule      opts ++ "\","
  , "         \"" ++ absLeanModule          opts ++ "\","
  , "         \"" ++ lexLeanModule          opts ++ "\","
  , "         \"" ++ parTablesLeanModule    opts ++ "\","
  , "         \"" ++ parSafeLeanModule      opts ++ "\","
  , "         \"" ++ parCompleteLeanModule  opts ++ "\","
  , "         \"" ++ parLeanModule          opts ++ "\","
  , "         \"" ++ printLeanModule        opts ++ "\"]"
  , ""
  , "[[lean_exe]]"
  , "name = \"" ++ exeName ++ "\""
  , "root = \"" ++ testLeanModule opts ++ "\""
  ]
  where
    projectName = lang opts
    exeName = "test" ++ lang opts

----------------------------------------------------------------------------
-- Optional Makefile target.  Defers to `lake build`.
----------------------------------------------------------------------------

makefile :: SharedOptions -> String -> Doc
makefile opts _basename = vcat $ map text
  [ "all: build"
  , ""
  , "# One-time setup: fetch LeanMenhir's transitive deps (just `repl`,"
  , "# which LeanMenhir keeps for its own LSP tooling)."
  , "setup:"
  , "\tlake update"
  , ""
  , "build:"
  , "\tlake build"
  , ""
  , "clean:"
  , "\trm -rf .lake build"
  , ""
  , "distclean: clean"
  , "\trm -f " ++ unwords generatedFiles
  ]
  where
    generatedFiles =
      [ runtimeLeanFile      opts
      , absLeanFile          opts
      , lexLeanFile          opts
      , parTablesLeanFile    opts
      , parSafeLeanFile      opts
      , parCompleteLeanFile  opts
      , parLeanFile          opts
      , printLeanFile        opts
      , testLeanFile         opts
      , lakeFile
      , leanToolchainFile
      ]
