{-# LANGUAGE LambdaCase #-}

{- |
Module      : BNFC.Backend.Lean.CFtoLeanPar
Description : Generate a Lean 4 recursive-descent parser with precedence
              climbing.

The transformation:

  * For each non-terminal `C` with maximum precedence `m`, emit one
    function `pCk` for every level `0 ≤ k ≤ m`.
  * Rules at level `k` whose first RHS element is `Ck` (left-recursive)
    are translated to a left-folding loop driven by `pC(k+1)`.
  * Rules at level `k` whose RHS does *not* start with `Ck` are turned
    into ordinary recursive-descent alternatives.
  * Coercion rules `_. Ck ::= Ck+1` simply delegate to `pC(k+1)`.
  * Pure parens-style `Ck ::= "(" C ")"` are common and handled as a
    normal alternative.
  * List categories `[C]` and rules involving them rely on three
    conventions BNFC already enforces:
      `[]   . [C] ::= ;`
      `(:)  . [C] ::= C ;`            (one-element list)
      `(:)  . [C] ::= C "sep" [C] ;`  (right-recursive)
      `(:[]). [C] ::= C ;`            (singleton)
    Any rule with `internal` flag is skipped (matching BNFC convention).

Limitations: this initial implementation handles all rule shapes
generated by the standard BNFC examples — additive, multiplicative,
unary, parenthesisation, list separators and built-in token literals.
Exotic constructions (mid-rule recursion at the same precedence,
backtracking-heavy ambiguous grammars) may need the user to factor
their grammar; in such cases the parser is permissive but may produce
a less helpful error message.
-}

module BNFC.Backend.Lean.CFtoLeanPar ( cf2Par ) where

import Data.List ( groupBy, sort, sortBy )
import Data.Function ( on )

import BNFC.CF
import BNFC.Backend.Lean.LeanUtil
  ( catToLeanType
  , constructorName
  , parserName
  , sanitizeLeanUpper
  )

cf2Par :: String -> String -> String -> String -> CF -> String
cf2Par modName absMod lexMod runtimeMod cf = unlines $ concat
  [ header
  , [ entryPointStub ]
  , [ "" ]
  , [ "mutual" ]
  , concatMap parserGroup parserGroups
  , [ "end" ]
  , [ "" ]
  , [ "/-- Parse a string by lexing it and running the entry-point parser. -/"
    , "def parse" ++ identCat firstE ++ " (input : String) : Except String " ++ catToLeanType firstE ++ " :="
    , "  match " ++ lexMod ++ ".tokenize input with"
    , "  | .error e   => .error (toString e)"
    , "  | .ok toks   =>"
    , "      match BNFC.Parser.run (" ++ parserName firstE ++ ") toks with"
    , "      | .ok x    => .ok x"
    , "      | .error e => .error (toString e)"
    ]
  , [ "" ]
  , [ "end " ++ modName ]
  ]
  where
    header =
      [ "import " ++ absMod
      , "import " ++ lexMod
      , "import " ++ runtimeMod
      , ""
      , "/-! Recursive-descent parser generated by BNFC.  Precedence is"
      , "    handled by `pCk`-style level functions; left-recursive rules"
      , "    are folded into loops. -/"
      , ""
      , "namespace " ++ modName
      , "open BNFC"
      , "open " ++ absMod
      , ""
      , "set_option linter.unusedVariables false"
      , "set_option maxRecDepth 1024"
      , ""
      ]
    firstE = firstEntry cf
    entryPointStub = "-- Entry point: " ++ identCat firstE ++ ""

    parserGroups :: [ParserGroup]
    parserGroups = computeGroups cf

    parserGroup :: ParserGroup -> [String]
    parserGroup g = renderGroup cf g

----------------------------------------------------------------------------
-- Group rules by category and precedence
----------------------------------------------------------------------------

data ParserGroup = ParserGroup
  { pgCat       :: Cat       -- ^ Normalised category, e.g. @Cat "Exp"@.
  , pgMaxPrec  :: Integer    -- ^ Highest precedence appearing.
  , pgLevels   :: [(Integer, [Rule])]  -- ^ Levels in ascending order.
  }

computeGroups :: CF -> [ParserGroup]
computeGroups cf =
  [ buildGroup cat rules
  | (cat, rules) <- byCat
  , isOrdinaryCat cat
  ]
  where
    -- All rules grouped by *normalised* lhs, only parsable.
    byCat :: [(Cat, [Rule])]
    byCat =
      [ (c, rs)
      | let allParsable = filter isParsable (cfgRules cf)
            grouped = groupBy ((==) `on` (normCat . valCat))
                    $ sortBy (compare `on` (catToStr . normCat . valCat))
                    $ allParsable
      , rs <- grouped
      , let c = normCat (valCat (head rs))
      ]

    isOrdinaryCat (Cat _)      = True
    isOrdinaryCat _            = False  -- skip token cats and lists

    buildGroup :: Cat -> [Rule] -> ParserGroup
    buildGroup cat rules =
      let precs = sort . map precRule $ rules
          maxP  = if null precs then 0 else last precs
          byPrec :: [(Integer, [Rule])]
          byPrec =
            [ (p, [ r | r <- rules, precRule r == p ])
            | p <- [0 .. maxP]
            ]
      in ParserGroup
           { pgCat = cat
           , pgMaxPrec = maxP
           , pgLevels = byPrec
           }

----------------------------------------------------------------------------
-- Render a parser group as a sequence of mutually recursive functions
----------------------------------------------------------------------------

renderGroup :: CF -> ParserGroup -> [String]
renderGroup cf (ParserGroup cat maxP levels) =
  concatMap renderLevel (reverse levels)
  ++ listParserFor cf cat
  where
    catName = identCat cat

    renderLevel :: (Integer, [Rule]) -> [String]
    renderLevel (p, rules) =
      let fnName = if p == 0 then "p" ++ catName else "p" ++ catName ++ show p
          higher | p == maxP = Nothing
                 | otherwise = Just ("p" ++ catName ++ show (p + 1))
          (leftRec, others) = partitionLeftRec cat p rules
          retType = catToLeanType cat
      in [ "  /-- Parser for category `" ++ catToStr cat ++ "` at precedence " ++ show p ++ ". -/"
         , "  partial def " ++ fnName ++ " : BNFC.Parser " ++ retType ++ " := do"
         ] ++ body retType higher leftRec others

    -- Build the body of one precedence level.
    body :: String -> Maybe String -> [Rule] -> [Rule] -> [String]
    body _retType higher leftRec others =
      case (higher, leftRec, others) of
        -- No alternatives at this level; just delegate up.
        (Just up, [], []) ->
          [ "    " ++ up ]
        -- Pure higher-only with extra non-recursive alternatives.
        (Just up, [], oth) ->
          [ "    " ++ orElseChain (map (atomCall cf) oth ++ [up]) ]
        -- Left-recursive with extras.
        (Just up, lrs, oth) ->
          let nonRec = orElseChain (map (atomCall cf) oth ++ [up])
              loop  = renderLeftRecLoop cf lrs
          in [ "    let lhs ← " ++ nonRec
             , loop
             ]
        -- Top precedence: no higher level.
        (Nothing, _, oth) ->
          [ "    " ++ orElseChain (map (atomCall cf) oth) ]

----------------------------------------------------------------------------
-- Render an "atom" (non-left-recursive) rule
----------------------------------------------------------------------------

atomCall :: CF -> Rule -> String
atomCall _cf r =
  let f = funName (funRule r)
      cat = normCat (valCat r)
      catName = sanitizeLeanUpper (catToStr cat)
  in case rhsRule r of
       []     -> "BNFC.Parser.pure " ++ catName ++ "." ++ constructorName f
       items  -> renderSeq f cat items

-- | Render a sequence of RHS items, building the constructor at the end.
renderSeq :: Fun -> Cat -> SentForm -> String
renderSeq f cat items
  | isCoercion f && length nonTerminals == 1 && null terminals =
      -- Pure coercion `_. C ::= D` (no terminals): delegate.
      "(" ++ parserNameForElement (head nonTerminals) ++ ")"
  | isCoercion f && length nonTerminals == 1 =
      -- Coercion-with-terminals (e.g. parenthesisation `_. C ::= "(" C ")"`):
      -- match the terminals but return the inner non-terminal unwrapped.
      let (binds, _, args) = foldr step ([], length nonTerminals, []) items
          callExpr = "BNFC.Parser.pure " ++ head args
      in "(do\n" ++ unlines (map ("    " ++) binds) ++ "    " ++ callExpr ++ ")"
  | otherwise = chain
  where
    nonTerminals = [ c | Left c <- items ]
    terminals    = [ s | Right s <- items ]

    chain :: String
    chain =
      let (binds, _, args) = foldr step ([], length nonTerminals, []) items
          ctor = sanitizeLeanUpper (catToStr cat) ++ "." ++ constructorName f
          callExpr =
            if null nonTerminals
              then "BNFC.Parser.pure " ++ ctor
              else "BNFC.Parser.pure (" ++ ctor ++ " " ++ unwordsArgs args ++ ")"
      in "(do\n" ++ unlines (map ("    " ++) binds) ++ "    " ++ callExpr ++ ")"

    -- Walk the RHS right-to-left to assign argument names.
    step :: Either Cat String -> ([String], Int, [String]) -> ([String], Int, [String])
    step (Right sym) (acc, n, args) =
      (("let _ ← BNFC.Parser.expectKeyword " ++ show sym) : acc, n, args)
    step (Left c) (acc, n, args) =
      let var = "x" ++ show n
          callP = parserNameForElement c
      in (("let " ++ var ++ " ← " ++ callP) : acc, n - 1, var : args)

unwordsArgs :: [String] -> String
unwordsArgs = unwords

----------------------------------------------------------------------------
-- Left-recursion handling
----------------------------------------------------------------------------

partitionLeftRec :: Cat -> Integer -> [Rule] -> ([Rule], [Rule])
partitionLeftRec cat p rules = (leftRec, others)
  where
    leftRec =
      [ r | r <- rules
          , not (isCoercion (funRule r))
          , case rhsRule r of
              (Left c : _) -> normCat c == cat && precCat c == p
              _            -> False
          , length [c | Left c <- rhsRule r] >= 2
            -- single-arg left-recursive (i.e. just a coercion-by-shape)
            -- has no useful action, skip
      ]
    others =
      [ r | r <- rules
          , r `notElem` leftRec
            -- skip pure single-arg coercion rules (they just delegate)
          , not (isPureCoercion cat p r)
      ]

isPureCoercion :: Cat -> Integer -> Rule -> Bool
isPureCoercion cat p r =
  case rhsRule r of
    [Left c] -> isCoercion (funRule r)
                 && normCat c == cat && precCat c == p + 1
    _        -> False

-- | Build the loop body for left-recursive rules at one precedence level.
renderLeftRecLoop :: CF -> [Rule] -> String
renderLeftRecLoop _cf lrs = unlines $ concat
  [ [ "    BNFC.Parser.pure (← loop lhs)" ]
  , [ "  where" ]
  , [ "    loop (acc : _) : BNFC.Parser _ := do" ]
  , [ "      " ++ orElseChain (map renderArm lrs ++ [ "BNFC.Parser.pure acc" ]) ]
  ]
  where
    renderArm :: Rule -> String
    renderArm r =
      let f = funName (funRule r)
          cat = normCat (valCat r)
          ctor = sanitizeLeanUpper (catToStr cat) ++ "." ++ constructorName f
          rhs = drop 1 (rhsRule r)  -- skip the leading recursive non-terminal
          (binds, _, args) = foldr stepArm ([], length [c | Left c <- rhs], []) rhs
          callBody = ctor ++ " acc " ++ unwords args
      in  "(do\n"
          ++ unlines (map ("        " ++) binds)
          ++ "        loop (" ++ callBody ++ "))"

    stepArm :: Either Cat String -> ([String], Int, [String]) -> ([String], Int, [String])
    stepArm (Right sym) (acc, n, args) =
      (("let _ ← BNFC.Parser.expectKeyword " ++ show sym) : acc, n, args)
    stepArm (Left c) (acc, n, args) =
      let var = "y" ++ show n
          callP = parserNameForElement c
      in (("let " ++ var ++ " ← " ++ callP) : acc, n - 1, var : args)

----------------------------------------------------------------------------
-- Parser names for RHS elements
----------------------------------------------------------------------------

parserNameForElement :: Cat -> String
parserNameForElement c = case c of
  TokenCat "Integer" -> "BNFC.Parser.expectIntLit"
  TokenCat "Double"  -> "BNFC.Parser.expectFloatLit"
  TokenCat "String"  -> "BNFC.Parser.expectStringLit"
  TokenCat "Char"    -> "BNFC.Parser.expectCharLit"
  TokenCat "Ident"   -> "BNFC.Parser.expectIdent"
  TokenCat t         -> "BNFC.Parser.expectUserTok " ++ show t
  ListCat inner      ->
    "(p" ++ identCat (ListCat inner) ++ ")"
  CoercCat s i       -> "p" ++ s ++ show i
  Cat s              -> "p" ++ s

----------------------------------------------------------------------------
-- List parsers
----------------------------------------------------------------------------

-- | When a category `C` has a list form `[C]`, emit a parser `pListC`.
--   The parser tries the rules:
--     * `[].   [C] ::= ;`        (empty list)
--     * `(:[]).[C] ::= C ;`       (singleton)
--     * `(:).  [C] ::= C "sep" [C] ;`  (separator)
--   We support these three by inspecting the rules at the list category.
listParserFor :: CF -> Cat -> [String]
listParserFor cf cat =
  let listCat = ListCat cat
      rules = rulesForCat cf listCat
  in if null rules then []
     else
       [ "  /-- Parser for `[" ++ catToStr cat ++ "]`. -/"
       , "  partial def p" ++ identCat listCat ++ " : BNFC.Parser (List " ++ catToLeanType cat ++ ") := do"
       , "    " ++ renderListBody cat rules
       ]

-- | Build the list-parser body.
renderListBody :: Cat -> [Rule] -> String
renderListBody cat rules =
  -- Heuristic: detect separator from the (:) rule.
  let consRules = [ r | r <- rules, isConsFun (funRule r) ]
      hasNil    = any isNilFun (map funRule rules)
      separator = case consRules of
        (r:_) -> case rhsRule r of
          [Left _, Right s, Left _] -> Just s
          _                         -> Nothing
        []    -> Nothing
      elemP = parserNameForElement cat
  in case (hasNil, separator) of
       (True,  Just s) ->
         "(BNFC.Parser.sepBy " ++ elemP ++ " (BNFC.Parser.expectKeyword " ++ show s ++ "))"
       (False, Just s) ->
         "(BNFC.Parser.sepBy1 " ++ elemP ++ " (BNFC.Parser.expectKeyword " ++ show s ++ "))"
       (True,  Nothing) ->
         "(BNFC.Parser.many " ++ elemP ++ ")"
       (False, Nothing) ->
         "(BNFC.Parser.many1 " ++ elemP ++ ")"

----------------------------------------------------------------------------
-- Misc
----------------------------------------------------------------------------

-- | Render a chain of `<|>` alternatives.
orElseChain :: [String] -> String
orElseChain []     = "BNFC.Parser.fail { line := 0, col := 0 } \"empty alternative\""
orElseChain [x]    = x
orElseChain (x:xs) = "(" ++ x ++ ") <|> (" ++ orElseChain xs ++ ")"
